### ISSUE TITLE
Cover size in Details view

### ISSUE THREAD

**Issue by chocolatechipcats** [darklinkpower/Mythic#7]
### Feature Description

I like this theme, but I personally find the cover image in Details view to be a bit small and hard to see. Would it be possible to add an option to make it larger, perhaps to better match the width of the install/play button?

Thank you.

### Screenshots

![2022-09-16 02_16_02-Window](https://user-images.githubusercontent.com/47759676/190561887-22ccf955-96a7-4be9-a020-40f9761eb889.png)

**Comment by chocolatechipcats** [comment]
alternately: what would I change to do it manually? I tried changing line 237 of DetailsViewGameOverview to
`                                                <Image Name="PART_ImageCover" Height="{Settings GameDetailsCoverHeight}" MaxWidth="600"`
but it failed to change...

**Comment by darklinkpower** [comment]
The Cover height is controller by this built-in Playnite setting 
![image](https://user-images.githubusercontent.com/1389286/194727247-74c9df98-1288-4491-9443-ac8288f06093.png)

As far as changing it to match the width, I'm not a fan of the idea since it would make the layout very inconsistent if there are covers of different heights, as it would move the buttons below up and down. It's the same reason why the Playnite setting controls the height instead of the width

**Comment by chocolatechipcats** [comment]
Thanks, I forgot that option was there.

Since I use 600x900 covers for most of my games, setting the height to a specific size makes it match the button width fair enough. So consider closed.
